/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ShoppingCartCal;

import service.ShoppingCartService;

public class ShoppingCart {
   public static void main(String args[]) {
	   
	   
   }
}
